name: Build
on: [push, pull_request]

jobs:
  build:
    name: Test App and Build Executables
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            target: windows
          - os: macos-latest
            target: macos
          - os: ubuntu-latest
            target: linux
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          pip install -U pyinstaller
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .
      
      - name: Compile application (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller src/main.py src/scanner.py --onefile
          mv dist/main.exe dist/MCreatorScanner.exe
      - name: Compile application (macOS, Linux)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          pyinstaller src/* --onefile
          mv dist/main dist/MCreatorScanner
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MCreatorScanner-${{ matrix.target }}
          path: dist/
